export const colors = {
  alertColorSucessLight: '#E0F6E9',
  alertColorSucessDark: '#32C069',
  alertColorInfoLight: '#E2F1FF',
  alertColorInfoDark: '#3A9FFC',
  alertColorErrorLight: '#FDE3E2',
  alertColorErrorDark: '#F2443E',
  alertColorWarningLight: '#FEF4E1',
  alertColorWarningDark: '#F9B137',
  neutralColorUltraDark: '#000',
  neutralColorDarkest: '#222',
  neutralColorLight: '#f4f4f6',
  neutralColorLightest: '#fefefe',
  neutralColorLighter: '#BBC8CE',
  neutralColorWhite: '#fff',
  neutralColorStandard: '#c7c9c7',
  neutralColorDark: '#666666',
  neutralColorBlueLight: '#d3dfef',
  brandcolorPrimaryLight: '#e4d9cb',
  brandColorPrimaryDark: '#a58154',
  overlayPrimaryColor: '#707070',
  primaryBackgroundColor: 'rgba(196, 196, 196, 0.25)',
  overlayOpacityBackgroundColorIOS: 'rgba(0,0,0,0.6)',
  overlayOpacityBackgroundColorAndroid: 'rgba(0,0,0,0.3)',
};
